package com.alst.mobile.domain.model

enum class SupportedLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
) {
    AFRIKAANS("af", "Afrikaans", "Afrikaans"),
    ARABIC("ar", "Arabic", "العربية"),
    BELARUSIAN("be", "Belarusian", "Беларуская"),
    BULGARIAN("bg", "Bulgarian", "Български"),
    BENGALI("bn", "Bengali", "বাংলা"),
    CATALAN("ca", "Catalan", "Català"),
    CZECH("cs", "Czech", "Čeština"),
    WELSH("cy", "Welsh", "Cymraeg"),
    DANISH("da", "Danish", "Dansk"),
    GERMAN("de", "German", "Deutsch"),
    GREEK("el", "Greek", "Ελληνικά"),
    ENGLISH("en", "English", "English"),
    ESPERANTO("eo", "Esperanto", "Esperanto"),
    SPANISH("es", "Spanish", "Español"),
    ESTONIAN("et", "Estonian", "Eesti"),
    PERSIAN("fa", "Persian", "فارسی"),
    FINNISH("fi", "Finnish", "Suomi"),
    FRENCH("fr", "French", "Français"),
    IRISH("ga", "Irish", "Gaeilge"),
    GALICIAN("gl", "Galician", "Galego"),
    GUJARATI("gu", "Gujarati", "ગુજરાતી"),
    HAUSA("ha", "Hausa", "Hausa"),
    HEBREW("he", "Hebrew", "עברית"),
    HINDI("hi", "Hindi", "हिन्दी"),
    CROATIAN("hr", "Croatian", "Hrvatski"),
    HUNGARIAN("hu", "Hungarian", "Magyar"),
    INDONESIAN("id", "Indonesian", "Bahasa Indonesia"),
    ICELANDIC("is", "Icelandic", "Íslenska"),
    ITALIAN("it", "Italian", "Italiano"),
    JAPANESE("ja", "Japanese", "日本語"),
    GEORGIAN("ka", "Georgian", "ქართული"),
    KANNADA("kn", "Kannada", "ಕನ್ನಡ"),
    KOREAN("ko", "Korean", "한국어"),
    LITHUANIAN("lt", "Lithuanian", "Lietuvių"),
    LATVIAN("lv", "Latvian", "Latviešu"),
    MACEDONIAN("mk", "Macedonian", "Македонски"),
    MARATHI("mr", "Marathi", "मराठी"),
    MALAY("ms", "Malay", "Bahasa Melayu"),
    MALTESE("mt", "Maltese", "Malti"),
    DUTCH("nl", "Dutch", "Nederlands"),
    NORWEGIAN("no", "Norwegian", "Norsk"),
    POLISH("pl", "Polish", "Polski"),
    PORTUGUESE("pt", "Portuguese", "Português"),
    ROMANIAN("ro", "Romanian", "Română"),
    RUSSIAN("ru", "Russian", "Русский"),
    SLOVAK("sk", "Slovak", "Slovenčina"),
    SLOVENIAN("sl", "Slovenian", "Slovenščina"),
    ALBANIAN("sq", "Albanian", "Shqip"),
    SWEDISH("sv", "Swedish", "Svenska"),
    SWAHILI("sw", "Swahili", "Kiswahili"),
    TAMIL("ta", "Tamil", "தமிழ்"),
    TELUGU("te", "Telugu", "తెలుగు"),
    THAI("th", "Thai", "ไทย"),
    TAGALOG("tl", "Tagalog", "Tagalog"),
    TURKISH("tr", "Turkish", "Türkçe"),
    UKRAINIAN("uk", "Ukrainian", "Українська"),
    URDU("ur", "Urdu", "اردو"),
    VIETNAMESE("vi", "Vietnamese", "Tiếng Việt"),
    CHINESE("zh", "Chinese", "中文");

    companion object {
        fun fromCode(code: String): SupportedLanguage? {
            return entries.find { it.code == code }
        }
    }
}
